spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        spring.json:
          trusted.packages: com.saturn.leankafka.*
        schema:
          registry:
            url: "http://127.0.0.1:8081"
